name: Build IPA
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Build Runner
        run: |
          flutter pub get
          # بناء التطبيق كمجلد (Framework) لتجنب فحص الشهادة
          flutter build ios --debug --no-codesign
          
          # الآن الحيلة اليدوية التي لا تفشل:
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r Runner.ipa Payload
          
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: My-App-IPA
          path: Runner.ipa
