- name: Build IPA (No Signing)
        run: |
          flutter pub get
          # هذا الأمر سيقوم ببناء ملف .app وتجاهل كل متطلبات التوقيع
          flutter build ios --debug --no-codesign
          
          # الآن سنقوم بتحويل الـ .app إلى ملف .ipa يدوياً لكي يقبله Sideloadly
          mkdir -p build/ios/iphoneos/Payload
          cp -r build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/
          cd build/ios/iphoneos
          zip -r instamod-baqer.ipa Payload
